rowpack -I 'http://public.source.civicknowledge.com/example.com/sources/simple-example-altnames.csv'
rowpack -I 'http://public.source.civicknowledge.com/example.com/sources/multisheet.xls#rent'
rowpack -I 'http://public.source.civicknowledge.com/example.com/sources/test_data.zip#simple-example.csv'
rowpack -I 'http://public.source.civicknowledge.com/example.com/sources/test_data.zip#renter_cost_excel07.xlsx'
rowpack -I 'http://public.source.civicknowledge.com/example.com/sources/unicode-utf8.csv'
rowpack -I 'http://public.source.civicknowledge.com/example.com/sources/renter_cost_excel07.xlsx'
rowpack -I 'http://public.source.civicknowledge.com/example.com/sources/renter_cost_excel97.xls'
rowpack -I 'http://public.source.civicknowledge.com/example.com/sources/renter_cost.csv'
rowpack -I 'http://public.source.civicknowledge.com/example.com/sources/renter_cost.tsv'
rowpack -I 'http://public.source.civicknowledge.com/example.com/sources/random-names.csv'
rowpack -I 'http://public.source.civicknowledge.com/example.com/sources/simple-example.csv.zip'
rowpack -I 'http://public.source.civicknowledge.com/example.com/sources/simple-example.csv'
rowpack -I 'http://public.source.civicknowledge.com/example.com/stats/simple_stats.csv'
rowpack -I 'http://public.source.civicknowledge.com/example.com/type_intuit/types_1.csv'
rowpack -I 'http://public.source.civicknowledge.com/example.com/type_intuit/types_2.csv'
rowpack -I 'http://public.source.civicknowledge.com/example.com/type_intuit/types_3.csv'
rowpack -I 'http://public.source.civicknowledge.com/example.com/row_intuit/headers_1.csv'
rowpack -I 'http://public.source.civicknowledge.com/example.com/row_intuit/headers_2.csv'
rowpack -I 'http://public.source.civicknowledge.com/example.com/row_intuit/headers_3.csv'
rowpack -I 'http://public.source.civicknowledge.com/example.com/row_intuit/headers_4.csv'
rowpack -I 'http+socrata://chhs.data.ca.gov/api/views/tthg-z4mf'

rowpack -I 'http://public.source.civicknowledge.com/example.com/sources/simple-example.foo' --filetype csv
rowpack -I 'http://public.source.civicknowledge.com/example.com/sources/test_data.foo#simple-example.csv'